# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/collecthistory.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 765)
        MainWindow.setMaximumSize(QtCore.QSize(1360, 765))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectBtn.setGeometry(QtCore.QRect(46, 12, 96, 96))
        self.connectBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/新前置字串/led_redoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/新前置字串/led_greenon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.connectBtn.setIcon(icon)
        self.connectBtn.setIconSize(QtCore.QSize(96, 96))
        self.connectBtn.setCheckable(True)
        self.connectBtn.setObjectName("connectBtn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(144, 12, 160, 50))
        self.groupBox.setObjectName("groupBox")
        self.userIDLine = QtWidgets.QLineEdit(self.groupBox)
        self.userIDLine.setGeometry(QtCore.QRect(4, 12, 150, 32))
        self.userIDLine.setInputMask("")
        self.userIDLine.setText("")
        self.userIDLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.userIDLine.setObjectName("userIDLine")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(144, 58, 160, 50))
        self.groupBox_2.setObjectName("groupBox_2")
        self.passwordLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.passwordLine.setGeometry(QtCore.QRect(4, 12, 150, 32))
        self.passwordLine.setText("")
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(16, 116, 325, 277))
        self.groupBox_3.setObjectName("groupBox_3")
        self.msgBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.msgBrowser.setGeometry(QtCore.QRect(10, 18, 305, 251))
        self.msgBrowser.setObjectName("msgBrowser")
        self.getWarrantLabel = QtWidgets.QGroupBox(self.centralwidget)
        self.getWarrantLabel.setGeometry(QtCore.QRect(14, 406, 325, 245))
        self.getWarrantLabel.setCheckable(False)
        self.getWarrantLabel.setObjectName("getWarrantLabel")
        self.calendar = QtWidgets.QCalendarWidget(self.getWarrantLabel)
        self.calendar.setGeometry(QtCore.QRect(10, 16, 301, 219))
        self.calendar.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.calendar.setMaximumDate(QtCore.QDate(2200, 12, 31))
        self.calendar.setGridVisible(False)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setDateEditEnabled(False)
        self.calendar.setObjectName("calendar")
        self.stockTree = QtWidgets.QTreeWidget(self.centralwidget)
        self.stockTree.setGeometry(QtCore.QRect(352, 80, 265, 635))
        self.stockTree.setObjectName("stockTree")
        self.stockTree.headerItem().setText(0, "1")
        self.stockTree.header().setVisible(True)
        self.stockTree.header().setCascadingSectionResizes(False)
        self.stockTree.header().setDefaultSectionSize(120)
        self.stockTree.header().setHighlightSections(False)
        self.stocktypeGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.stocktypeGroup.setEnabled(False)
        self.stocktypeGroup.setGeometry(QtCore.QRect(350, 8, 265, 67))
        self.stocktypeGroup.setObjectName("stocktypeGroup")
        self.semBtn = QtWidgets.QPushButton(self.stocktypeGroup)
        self.semBtn.setGeometry(QtCore.QRect(8, 14, 48, 48))
        self.semBtn.setCheckable(True)
        self.semBtn.setChecked(True)
        self.semBtn.setObjectName("semBtn")
        self.otcBtn = QtWidgets.QPushButton(self.stocktypeGroup)
        self.otcBtn.setGeometry(QtCore.QRect(58, 14, 48, 48))
        self.otcBtn.setCheckable(True)
        self.otcBtn.setObjectName("otcBtn")
        self.futuresBtn = QtWidgets.QPushButton(self.stocktypeGroup)
        self.futuresBtn.setGeometry(QtCore.QRect(108, 14, 48, 48))
        self.futuresBtn.setCheckable(True)
        self.futuresBtn.setObjectName("futuresBtn")
        self.optionBtn = QtWidgets.QPushButton(self.stocktypeGroup)
        self.optionBtn.setGeometry(QtCore.QRect(158, 14, 48, 48))
        self.optionBtn.setCheckable(True)
        self.optionBtn.setObjectName("optionBtn")
        self.esmBtn = QtWidgets.QPushButton(self.stocktypeGroup)
        self.esmBtn.setGeometry(QtCore.QRect(208, 14, 48, 48))
        self.esmBtn.setCheckable(True)
        self.esmBtn.setObjectName("esmBtn")
        self.saveAllStocks = QtWidgets.QPushButton(self.centralwidget)
        self.saveAllStocks.setGeometry(QtCore.QRect(16, 658, 113, 47))
        self.saveAllStocks.setObjectName("saveAllStocks")
        self.saveDayKLine = QtWidgets.QPushButton(self.centralwidget)
        self.saveDayKLine.setEnabled(False)
        self.saveDayKLine.setGeometry(QtCore.QRect(144, 658, 113, 47))
        self.saveDayKLine.setObjectName("saveDayKLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIntraCMD = QtWidgets.QAction(MainWindow)
        self.actionIntraCMD.setCheckable(True)
        self.actionIntraCMD.setChecked(False)
        self.actionIntraCMD.setEnabled(True)
        self.actionIntraCMD.setObjectName("actionIntraCMD")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.actionWarrant = QtWidgets.QAction(MainWindow)
        self.actionWarrant.setObjectName("actionWarrant")
        self.actionStockKLine = QtWidgets.QAction(MainWindow)
        self.actionStockKLine.setCheckable(True)
        self.actionStockKLine.setObjectName("actionStockKLine")
        self.menuFile.addAction(self.action_Exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.action_Exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CollectHistory"))
        self.groupBox.setTitle(_translate("MainWindow", "User"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Password"))
        self.groupBox_3.setTitle(_translate("MainWindow", "System Message"))
        self.getWarrantLabel.setTitle(_translate("MainWindow", "Get Warrant"))
        self.stocktypeGroup.setTitle(_translate("MainWindow", "StockType"))
        self.semBtn.setText(_translate("MainWindow", "SEM"))
        self.otcBtn.setText(_translate("MainWindow", "OTC"))
        self.futuresBtn.setText(_translate("MainWindow", "Futures"))
        self.optionBtn.setText(_translate("MainWindow", "Option"))
        self.esmBtn.setText(_translate("MainWindow", "ESM"))
        self.saveAllStocks.setText(_translate("MainWindow", "Save Stocks KLine\n"
"( 1 min)"))
        self.saveDayKLine.setText(_translate("MainWindow", "Save Stocks KLine\n"
"(Day KLin)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionIntraCMD.setText(_translate("MainWindow", "IntraCMD"))
        self.action_Exit.setText(_translate("MainWindow", "Exit"))
        self.actionWarrant.setText(_translate("MainWindow", "Warrant"))
        self.actionStockKLine.setText(_translate("MainWindow", "Stock - Day-KLine"))

import capital_rc
